### ISSUE TITLE
Chore(cli dev): Show what port the bot is running on when starting it up.

### ISSUE THREAD

**Issue by Nazeofel** [Wave-Play/robo.js#190]
Update dev file and start file in the robo CLI so they display the port the bot is currently running on.

We could use the .env file to display the port it is using, or fallback to default when there is nothing in it.

**Comment by Pkmmte** [comment]
Doesn't it already do that? See screenshot attached: 
<img width="556" alt="Screenshot 2024-01-12 at 10 54 09 PM" src="https://github.com/Wave-Play/robo.js/assets/3953360/b67b74b8-dfbf-4c31-b190-ed689afc6e3c">

I'm assuming you're talking about the API plugin because bots themselves are socket-based and don't listen to incoming connections via ports. Rather, they are the ones to initiate the connection.

**Comment by Nazeofel** [comment]
It works with the plugin-api indeed, but we had users concerned about what port the actual bot was running on, I'll surely let them know about it then.
