### ISSUE TITLE
[do we need it?]   particular button events ?

### ISSUE THREAD

**Issue by ArnavK-09** [Wave-Play/robo.js#207]
instead of validating buttons with id and event type in events file 
![image](https://github.com/Wave-Play/robo.js/assets/69188140/e46bd549-3859-4243-ad28-a3f136372078)

instead we can add buttons in following files with proper events!!

`src/buttons/unban.ts`

or 

`src/events/unban.button.ts`

**Comment by Pkmmte** [comment]
@ArnavK-09 Mmm, I'm not quite sure what you mean. Are you suggesting we place these button files inside the `/src/buttons` directory?

I'm not against it, but the reason we place these button callbacks in `/src/events/interactionCreate` is because they're all subsets of the `interactionCreate` Discord event. We'd still need to forward them somehow, preferably in a decentralized fashion.

**Comment by OfficialCRUGG** [comment]
Well, isn't that the same thing you do with slash commands already? They're also triggered by `interactionCreate`, but forwarded to the individual files in `src/commands`. A `src/buttons` is my number 1 feature request.

**Comment by Pkmmte** [comment]
@OfficialCRUGG  Ah, I understand what you both mean now. Yes, I think that'd be an excellent feature, especially if there's an automatic way to pass the state to those.

We'll definitely look into supporting this!

**Comment by ArnavK-09** [comment]
Yup

**Comment by ArnavK-09** [comment]
Discussed in discord

Also just realised there is template to reach similiar results

https://github.com/Wave-Play/robo.js/tree/main/templates%2Fdiscord-bots%2Fmrjawesome-dev-toolkit-js
